name: Feature request
description: Request a new feature/functionality to add in SportShield
title: "Feature request: [Your request]"
labels: [Feature request]
assignees:
  - DavidCC812
body:
  - type: markdown
    attributes:
      value: |
        We can only implement features following the primary use of SportShield
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what feature you want to be implemented.
      placeholder: A good addition would be...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.